version: "3.8"
services:
    server:
        build: .
        image: music-server
        container_name: music-server
        volumes:
            - .:/app

        ports:
            - "3000:3000"
        depends_on:
            - mongo

        environment:
            - MONGODB_URL=mongodb://mongo:27017/music

    mongo:
        image: mongo:7
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
